### ISSUE TITLE
No more .tss support since 0.3.0 update?

### ISSUE THREAD

**Issue by nuno** [dbankier/vscode-titanium#2]
Hey David, I just update your version on my "VSC 1.9.1"  to  0.3.0, and I cant get the  .tss association.

Wondering if I have to do more configurations?

Thanks!

```
// Place your settings in this file to overwrite the default settings
{
   "alloy.style": ".tss",
    "alloy.view": ".xml",
    "alloy.controller":  ".js",
    "editor.fontSize": 13,
    "window.showFullPath": true,
    "terminal.external.osxExec": "iTerm.app"
}


EDITED:
Or maybe never had and I forgot :(  
http://sharebucketapp.com/WUzZjgyNTlhN2M0MTUyO

**Comment by dbankier** [comment]
This should be fixed with the most recent version?

**Comment by nuno** [comment]
@dbankier Yes is fixed, thanks great work, as always!

**Comment by dbankier** [comment]
Don't thank me, the tss work was thanks to @axmo in https://github.com/dbankier/vscode-titanium/pull/3
